// swift-tools-version: 6.2
import PackageDescription

let package = Package(
    name: "ApplePurchaseReceiptVerifier",
    products: [.library(name: "ApplePurchaseReceiptVerifier", targets: ["ApplePurchaseReceiptVerifier"])],
    targets: [
        // The Rust core, prebuilt, as an SE-0482 artifact bundle (no unsafeFlags, no Rust toolchain needed)
        .binaryTarget(name: "AprvFFI", path: "AprvFFI.artifactbundle"),
        // Generated by uniffi-bindgen, committed as-is
        .target(name: "ApplePurchaseReceiptVerifier", dependencies: ["AprvFFI"],
                swiftSettings: [.swiftLanguageMode(.v5)]),
        .executableTarget(name: "Smoke", dependencies: ["ApplePurchaseReceiptVerifier"]),
    ]
)
