// Regenerates src/roots-data.ts from the DER files in certs/.
// Run after any change to certs/ (the apple-root-watch workflow is what
// tells you Apple changed them); CI re-runs this and fails on a diff.
//   node scripts/gen-roots.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const NAMES = ['AppleIncRootCertificate.cer', 'AppleRootCA-G2.cer', 'AppleRootCA-G3.cer'];
const wrap = (s) =>
  s
    .match(/.{1,76}/g)
    .map((l) => `  '${l}' +`)
    .join('\n')
    .replace(/ \+$/, '');

const body = NAMES.map((name) => {
  const der = readFileSync(fileURLToPath(new URL(`../certs/${name}`, import.meta.url)));
  const constant = name
    .replace(/\.cer$/, '')
    .replace(/-/g, '_')
    .toUpperCase();
  return `/** ${name}, DER, base64. */\nconst ${constant} =\n${wrap(der.toString('base64'))};\n`;
}).join('\n');

const out = `// GENERATED by scripts/gen-roots.mjs from certs/*.cer — do not edit by hand.
// The roots are inlined rather than read from certs/ at call time so the
// package works where there is no filesystem: Cloudflare Workers and every
// other bundled runtime. certs/ stays the reviewable source of truth and
// apple-root-watch still diffs it against Apple's PKI page weekly.

${body}
export const APPLE_ROOT_DER_BASE64: readonly string[] = [
  APPLEINCROOTCERTIFICATE,
  APPLEROOTCA_G2,
  APPLEROOTCA_G3,
];
`;
writeFileSync(fileURLToPath(new URL('../src/roots-data.ts', import.meta.url)), out);
