using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

// Regenerates src/ApplePurchaseReceiptVerifier/Internal/AppleRootData.cs from
// the repo-root certs/ directory. certs/ stays the reviewable source of truth;
// CI runs this and fails on a diff, so the compiled-in copy can never drift.
//
//   dotnet run --project dotnet/tools/GenerateRootData -- <repoRoot>
internal static class Program
{
    private static readonly string[] Roots =
    {
        "AppleIncRootCertificate.cer",
        "AppleRootCA-G2.cer",
        "AppleRootCA-G3.cer",
    };

    private static int Main(string[] args)
    {
        string repoRoot = args.Length > 0 ? args[0] : FindRepoRoot();
        string certsDirectory = Path.Combine(repoRoot, "certs");
        string output = Path.Combine(
            repoRoot, "dotnet", "src", "ApplePurchaseReceiptVerifier", "Internal", "AppleRootData.cs");

        StringBuilder source = new StringBuilder();
        source.AppendLine("// <auto-generated>");
        source.AppendLine("//   Generated by dotnet/tools/GenerateRootData from the repo-root certs/");
        source.AppendLine("//   directory. Do not edit by hand: CI regenerates this file and fails on");
        source.AppendLine("//   a diff. The bytes are compiled in as source constants rather than as an");
        source.AppendLine("//   embedded resource or a file on disk, so they survive ILLink trimming,");
        source.AppendLine("//   single-file publish and IL2CPP resource stripping with no configuration.");
        source.AppendLine("// </auto-generated>");
        source.AppendLine();
        source.AppendLine("namespace ApplePurchaseReceiptVerifier.Internal");
        source.AppendLine("{");
        source.AppendLine("    internal static class AppleRootData");
        source.AppendLine("    {");

        List<string> names = new List<string>();
        foreach (string file in Roots)
        {
            string identifier = Identifier(file);
            names.Add(identifier);
            string base64 = Convert.ToBase64String(File.ReadAllBytes(Path.Combine(certsDirectory, file)));
            source.AppendLine("        /// <summary>certs/" + file + "</summary>");
            source.AppendLine("        internal const string " + identifier + " =");
            foreach (string chunk in Wrap(base64, 96))
            {
                source.AppendLine("            \"" + chunk + "\" +");
            }

            source.Length -= (" +" + Environment.NewLine).Length;
            source.AppendLine(";");
            source.AppendLine();
        }

        source.AppendLine("        /// <summary>Every pinned root, in the order certs/ lists them.</summary>");
        source.AppendLine("        internal static readonly string[] All =");
        source.AppendLine("        {");
        foreach (string name in names)
        {
            source.AppendLine("            " + name + ",");
        }

        source.AppendLine("        };");
        source.AppendLine("    }");
        source.AppendLine("}");

        string text = source.ToString().Replace("\r\n", "\n");
        Directory.CreateDirectory(Path.GetDirectoryName(output)!);
        File.WriteAllText(output, text);
        Console.WriteLine("wrote " + output);
        return 0;
    }

    private static IEnumerable<string> Wrap(string value, int width)
    {
        for (int i = 0; i < value.Length; i += width)
        {
            yield return value.Substring(i, Math.Min(width, value.Length - i));
        }
    }

    private static string Identifier(string file)
    {
        StringBuilder id = new StringBuilder();
        foreach (char c in Path.GetFileNameWithoutExtension(file))
        {
            if (char.IsLetterOrDigit(c))
            {
                id.Append(c);
            }
        }

        return id.ToString();
    }

    private static string FindRepoRoot()
    {
        DirectoryInfo? directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null)
        {
            if (Directory.Exists(Path.Combine(directory.FullName, "certs"))
                && File.Exists(Path.Combine(directory.FullName, "PLAN.md")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        throw new InvalidOperationException("could not locate the repository root");
    }
}
