#!/usr/bin/env ruby
# frozen_string_literal: true

# Regenerates lib/apple_purchase_receipt_verifier/roots_data.rb from certs/.
# The anchors ship *inlined* rather than read from disk at call time, so the
# gem works from a read-only or bundled deployment and a stripped `certs/`
# cannot silently produce a verifier with no trust anchors (S7).
#
# CI runs this and fails on a diff, so a certs/ change that forgets to
# regenerate cannot ship stale trust anchors.

require "base64"

root = File.expand_path("..", __dir__)
names = %w[AppleIncRootCertificate AppleRootCA-G2 AppleRootCA-G3]

entries = names.map do |name|
  der = File.binread(File.join(root, "certs", "#{name}.cer"))
  b64 = [der].pack("m0")
  wrapped = b64.scan(/.{1,76}/).map { |line| "      \"#{line}\"" }.join(" \\\n")
  "    # #{name}.cer\n#{wrapped}"
end

File.write(File.join(root, "lib", "apple_purchase_receipt_verifier", "roots_data.rb"), <<~RUBY_SOURCE)
  # frozen_string_literal: true

  # GENERATED by script/gen_roots.rb from certs/. Do not edit by hand.
  #
  # The three published Apple root certificates
  # (https://www.apple.com/certificateauthority/), inlined as base64 DER so the
  # gem carries its trust anchors in its own code rather than reading them from
  # disk when a verifier is built (PLAN.md D15, cross-port rule S7).

  module ApplePurchaseReceiptVerifier
    # @api private
    APPLE_ROOT_DER_BASE64 = [
  #{entries.join(",\n")}
    ].freeze
  end
RUBY_SOURCE

puts "wrote roots_data.rb (#{names.size} roots)"
